### ISSUE TITLE
No Alive Noes found in your cluster

### ISSUE THREAD

**Issue by tcagkansokmen** [babenkoivan/elastic-scout-driver#33] opened 2021-09-02 05:42 UTC
| Software         | Version
| --------------| ---------------
| PHP                 | 7.4
| Elasticsearch  | 7.14
| Laravel            | 8.12
| Laravel Scout | 9.2

I am using elastic cloud.

My elastic.client.php file is;
   ```
 'hosts' => [
      'https://username:password@blabla-central1.gcp.cloud.es.io/api/as/v1/engines/myproject/documents'
]
```

But it returns; 
No Alive Noes found in your cluster

I couldnt understand how to connect "elastic cloud" system.
Looks like no way to make it

**Comment by babenkoivan** [comment] 2021-09-16 17:03
Hey @tcagkansokmen, this question is related to [elastic/elasticsearch-php](https://github.com/elastic/elasticsearch-php) configuration, so maybe it's better to open an issue there. I'm closing this as a duplicate of https://github.com/babenkoivan/elastic-client/issues/5.

**Closed by babenkoivan** 2021-09-16 17:03 UTC
Labels: bug
